---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-lb
spec:
  selector:
    app: echoserver
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
